name: SillinessLimiter
version: '${project.version}'
main: justaplugin.sillinesslimiter.IPLock
api-version: '1.20'
commands:
    silly-limit:
        description: "Locking IP on your account"
        usage: /silly-limit
        permission: justaplugin.sillinesslimiter.sillylimit
    silly-unlimit:
        description: "Unlocking IP on your account"
        usage: /silly-unlimit
        permission: justaplugin.sillinesslimiter.sillyunlimit
    silly-reload:
        description: "Reload SillinessLimiter config and language"
        usage: /silly-reload
        permission: justaplugin.sillinesslimiter.sillyreload
    silly-confirm:
        description: "Confirming IP change"
        usage: /silly-confirm
        permission: justaplugin.sillinesslimiter.sillyconfirm
    silly-deny:
        description: "Denying IP change"
        usage: /silly-deny
        permission: justaplugin.sillinesslimiter.sillydeny
    silly-list:
        description: "List of linked IPs"
        usage: /silly-list
        permission: justaplugin.sillinesslimiter.sillylist