name: SillinessLimiter
version: '${project.version}'
main: justaplugin.sillinesslimiter.IPLock
api-version: '1.20'
commands:
    limit-silly:
        description: "Locking IP on your account"
        usage: /limit-silly
        permission: justaplugin.sillinesslimiter.limitsilly
    unlimit-silly:
        description: "Unlocking IP on your account"
        usage: /unlimit-silly
        permission: justaplugin.sillinesslimiter.unlimitsilly
    silly-reload:
        description: "Reload Silliness limiter config"
        usage: /reload-silly
        permission: justaplugin.sillinesslimiter.sillyreload